const ActionTypes = {
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_FEEDINGS: 'UPDATE_FEEDINGS',
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  UPDATE_FEEDING_START: 'UPDATE_FEEDING_START',
  UPDATE_FEEDING_SUCCESS: 'UPDATE_FEEDING_SUCCESS',
  UPDATE_FEEDING_FAIL: 'UPDATE_FEEDING_FAIL'
};

export default ActionTypes;
